name: base
description: base
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #region riverpod
  flutter_hooks: ^0.21.3+1
  flutter_riverpod: ^3.0.3
  hooks_riverpod: ^3.0.3
  riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  #endregion

  # freezed_annotation: ^3.1.0
  cached_network_image: ^3.4.1 # android ios macos
  cached_network_image_platform_interface: ^4.1.1 # android ios macos
  collection: ^1.19.1
  crypto: ^3.0.6
  # custom_platform_device_id: ^1.0.8
  flutter_device_id: ^1.0.1
  # android_id: ^0.5.1
  device_info_plus: ^12.3.0
  dio: ^5.9.0
  dynamic_app_icon_flutter: ^0.0.3 # android ios
  flutter_cache_manager: ^3.4.1 # android ios macos
  intl: ^0.20.2
  isar_community: ^3.3.0
  isar_community_flutter_libs: ^3.3.0 # contains the binaries
  json_annotation: ^4.9.0
  logging: ^1.3.0
  lpinyin: ^2.0.3
  meta: ^1.16.0
  mime: ^2.0.0
  package_info_plus: ^8.3.1
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1 # android ios windows
  quiver: ^3.2.2
  recase: ^4.1.0
  retrofit: ^4.9.0
  shimmer: ^3.0.0
  stack_trace: ^1.12.1
  top_snackbar_flutter: ^3.3.0
  url_launcher: ^6.3.2
  uuid: ^4.5.1
  wakelock_plus: ^1.3.2
  webview_flutter: ^4.13.0 # android ios
  timeago: ^3.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  #region lint
  # custom_lint: ^0.7.1
  # riverpod_lint: ^2.3.12
  flutter_lints: ^6.0.0
  #endregion

  #region generator
  # go_router_builder: ^2.6.0
  flutter_gen_runner: ^5.11.0
  # freezed: ^3.1.0
  isar_community_generator: ^3.3.0
  json_serializable: ^6.9.5
  retrofit_generator: ^10.0.0
  riverpod_generator: ^3.0.3
  #endregion

  #region tool
  analyzer: ^7.6.0
  build_runner: ^2.7.1
  built_collection: ^5.1.1
  code_builder: ^4.10.1
  dart_style: ^3.1.1
  excel: ^4.0.6
  pub_semver: ^2.2.0
  pubspec_parse: ^1.5.0
  #endregion

dependency_overrides:
  excel:
    git:
      url: https://github.com/justkawal/excel
      ref: 751dfc597c893a0b34eccfe6921f126e03a5c683
  archive: ^4.0.7 # excel
  retrofit: 4.9.0 # 4.9.1 的ParseErrorLogger.logError多了个参数, 需要retrofit_generator: ^10.2.0, 但是又需要analyzer: ^9.0.0

flutter:
  # generate: true # flutter-l10n
  uses-material-design: true

# 配置参考: https://github.com/FlutterGen/flutter_gen/blob/main/examples/example/pubspec.yaml#L114
flutter_gen:
  parse_metadata: true
  fonts:
    enabled: false

# 配置参考: https://pub.dev/packages/intl_utils#usage
# flutter_intl:
#   enabled: true # Required. Must be set to true to activate the package. Default: false
#   class_name: S # Optional. Sets the name for the generated localization class. Default: S
#   main_locale: en # Optional. Sets the main locale used for generating localization files. Provided value should consist of language code and optional script and country codes separated with underscore (e.g. 'en', 'en_GB', 'zh_Hans', 'zh_Hans_CN'). Default: en
#   arb_dir: lib/l10n # Optional. Sets the directory of your ARB resource files. Provided value should be a valid path on your system. Default: lib/l10n
#   output_dir: lib/gen # Optional. Sets the directory of generated localization files. Provided value should be a valid path on your system. Default: lib/generated
#   use_deferred_loading: false # Optional. Must be set to true to generate localization code that is loaded with deferred loading. Default: false
